spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hodor2333/springcloudconfig/
          search-paths: respo
          username:
          password:
      lable: master

server:
  port: 8767

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
